### PR TITLE
Update axios to fix follow-redirects vulnerability

### PR DESCRIPTION
**Pull request by dragosroua**
Axios dependency `follow-redirects` is tagged as high vulnerability in this [advisory](https://github.com/advisories/GHSA-cph5-m8f7-6c5x). I was using `starport-vuex` in a project, which has `@confio/ts-relayer` as a dependancy and got flagged by Github dependabot. After digging through, this appeared. 

While running `npm audit` the vulnerability is tagged as solved in `axios >= 0.21.2`. The version in this repo is `0.21.4` atm, but for some reason, `npm audit` is still flagging it as unresolved. Bumping axios to the latest version.

### CODE REVIEW

**Comment by ethanfrey** [comment]
Thank you for the contribution.
Can you please update the package.lock so this passes CI?

```
yarn install --frozen-lockfile
yarn install v1.22.15
[1/5] Validating package.json...
[2/5] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by dragosroua** [comment]
Done.

**Comment by dragosroua** [comment]
Let me know if you can merge this or if there's something else needed on my part. Cheers.

**Comment by webmaster128** [comment]
Thank you for the report. In #217 you find a patch that specifically bumps the affected dependency.

**Pull request closed without merging**
